<Project>
  <PropertyGroup>
    <Description>Extends the CSSOM from the core AngleSharp library.</Description>
    <Product>AngleSharp.Css</Product>
    <Version>1.0.2</Version>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <SignAssembly>true</SignAssembly>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)\Key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
</Project>
